'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Splitty.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property _7z() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7z", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bluray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bluray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property custom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("custom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property dvd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dvd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Elektro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Elektro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Want to cancel the current operation?.
        '''</summary>
        Public ReadOnly Property ENG01() As String
            Get
                Return ResourceManager.GetString("ENG01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drop a folder here....
        '''</summary>
        Public ReadOnly Property ENG02() As String
            Get
                Return ResourceManager.GetString("ENG02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The output directory can&apos;t be the same as Input directory.
        '''</summary>
        Public ReadOnly Property ENG03() As String
            Get
                Return ResourceManager.GetString("ENG03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The input directory can&apos;t be the same as output directory.
        '''</summary>
        Public ReadOnly Property ENG04() As String
            Get
                Return ResourceManager.GetString("ENG04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to That&apos;s not a directory!.
        '''</summary>
        Public ReadOnly Property ENG05() As String
            Get
                Return ResourceManager.GetString("ENG05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copying {0} of {2} files... {1}%.
        '''</summary>
        Public ReadOnly Property ENG06() As String
            Get
                Return ResourceManager.GetString("ENG06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating ISO image for disc #.
        '''</summary>
        Public ReadOnly Property ENG07() As String
            Get
                Return ResourceManager.GetString("ENG07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Storing {0} of {2} volumes....
        '''</summary>
        Public ReadOnly Property ENG08() As String
            Get
                Return ResourceManager.GetString("ENG08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All files splitted OK.
        '''</summary>
        Public ReadOnly Property ENG09() As String
            Get
                Return ResourceManager.GetString("ENG09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A utility that allows you to split a directory into multiple folders of a specific size to burn it later..
        '''</summary>
        Public ReadOnly Property ENG10() As String
            Get
                Return ResourceManager.GetString("ENG10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Input :.
        '''</summary>
        Public ReadOnly Property ENG11() As String
            Get
                Return ResourceManager.GetString("ENG11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output :.
        '''</summary>
        Public ReadOnly Property ENG12() As String
            Get
                Return ResourceManager.GetString("ENG12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capacity.
        '''</summary>
        Public ReadOnly Property ENG13() As String
            Get
                Return ResourceManager.GetString("ENG13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mode.
        '''</summary>
        Public ReadOnly Property ENG14() As String
            Get
                Return ResourceManager.GetString("ENG14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Public ReadOnly Property ENG15() As String
            Get
                Return ResourceManager.GetString("ENG15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data   :.
        '''</summary>
        Public ReadOnly Property ENG16() As String
            Get
                Return ResourceManager.GetString("ENG16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discs :.
        '''</summary>
        Public ReadOnly Property ENG17() As String
            Get
                Return ResourceManager.GetString("ENG17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPLIT.
        '''</summary>
        Public ReadOnly Property ENG18() As String
            Get
                Return ResourceManager.GetString("ENG18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STOP.
        '''</summary>
        Public ReadOnly Property ENG19() As String
            Get
                Return ResourceManager.GetString("ENG19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Public ReadOnly Property ENG20() As String
            Get
                Return ResourceManager.GetString("ENG20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom size.
        '''</summary>
        Public ReadOnly Property ENG21() As String
            Get
                Return ResourceManager.GetString("ENG21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About....
        '''</summary>
        Public ReadOnly Property ENG22() As String
            Get
                Return ResourceManager.GetString("ENG22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Public ReadOnly Property ENG23() As String
            Get
                Return ResourceManager.GetString("ENG23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Public ReadOnly Property ENG24() As String
            Get
                Return ResourceManager.GetString("ENG24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spanish.
        '''</summary>
        Public ReadOnly Property ENG25() As String
            Get
                Return ResourceManager.GetString("ENG25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  of custom storage.
        '''</summary>
        Public ReadOnly Property ENG26() As String
            Get
                Return ResourceManager.GetString("ENG26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Storing {0} of {2} volumes... {1}%.
        '''</summary>
        Public ReadOnly Property ENG27() As String
            Get
                Return ResourceManager.GetString("ENG27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split aborted.
        '''</summary>
        Public ReadOnly Property ENG28() As String
            Get
                Return ResourceManager.GetString("ENG28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom size cannot be greather than input directory size..
        '''</summary>
        Public ReadOnly Property ENG29() As String
            Get
                Return ResourceManager.GetString("ENG29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Directory size: .
        '''</summary>
        Public ReadOnly Property ENG30() As String
            Get
                Return ResourceManager.GetString("ENG30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom size: .
        '''</summary>
        Public ReadOnly Property ENG31() As String
            Get
                Return ResourceManager.GetString("ENG31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File changes have been made in source folder, Want to reload the folder now?.
        '''</summary>
        Public ReadOnly Property ENG32() As String
            Get
                Return ResourceManager.GetString("ENG32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Quiere cancelar la operación?.
        '''</summary>
        Public ReadOnly Property SPA01() As String
            Get
                Return ResourceManager.GetString("SPA01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arrastre un directorio aquí....
        '''</summary>
        Public ReadOnly Property SPA02() As String
            Get
                Return ResourceManager.GetString("SPA02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El directorio de salida no puede ser el mismo que el directorio de entrada.
        '''</summary>
        Public ReadOnly Property SPA03() As String
            Get
                Return ResourceManager.GetString("SPA03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El directorio de entrada no puede ser el mismo que el directorio de salida.
        '''</summary>
        Public ReadOnly Property SPA04() As String
            Get
                Return ResourceManager.GetString("SPA04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Eso no es un directorio!.
        '''</summary>
        Public ReadOnly Property SPA05() As String
            Get
                Return ResourceManager.GetString("SPA05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copiando {0} de {2} archivos... {1}%.
        '''</summary>
        Public ReadOnly Property SPA06() As String
            Get
                Return ResourceManager.GetString("SPA06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creando imagen ISO del disco #.
        '''</summary>
        Public ReadOnly Property SPA07() As String
            Get
                Return ResourceManager.GetString("SPA07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Almacenando {0} de {2} volumenes....
        '''</summary>
        Public ReadOnly Property SPA08() As String
            Get
                Return ResourceManager.GetString("SPA08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Todos los archivos se han partido corréctamente..
        '''</summary>
        Public ReadOnly Property SPA09() As String
            Get
                Return ResourceManager.GetString("SPA09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Una utilidad que le permite partir un directorio en varias carpetas de un tamaño específico para grabarlas..
        '''</summary>
        Public ReadOnly Property SPA10() As String
            Get
                Return ResourceManager.GetString("SPA10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Origen :.
        '''</summary>
        Public ReadOnly Property SPA11() As String
            Get
                Return ResourceManager.GetString("SPA11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Destino :.
        '''</summary>
        Public ReadOnly Property SPA12() As String
            Get
                Return ResourceManager.GetString("SPA12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capacidad.
        '''</summary>
        Public ReadOnly Property SPA13() As String
            Get
                Return ResourceManager.GetString("SPA13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modo.
        '''</summary>
        Public ReadOnly Property SPA14() As String
            Get
                Return ResourceManager.GetString("SPA14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Información.
        '''</summary>
        Public ReadOnly Property SPA15() As String
            Get
                Return ResourceManager.GetString("SPA15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datos   :.
        '''</summary>
        Public ReadOnly Property SPA16() As String
            Get
                Return ResourceManager.GetString("SPA16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Discos :.
        '''</summary>
        Public ReadOnly Property SPA17() As String
            Get
                Return ResourceManager.GetString("SPA17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PARTIR.
        '''</summary>
        Public ReadOnly Property SPA18() As String
            Get
                Return ResourceManager.GetString("SPA18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PARAR.
        '''</summary>
        Public ReadOnly Property SPA19() As String
            Get
                Return ResourceManager.GetString("SPA19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copia.
        '''</summary>
        Public ReadOnly Property SPA20() As String
            Get
                Return ResourceManager.GetString("SPA20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tamaño pers..
        '''</summary>
        Public ReadOnly Property SPA21() As String
            Get
                Return ResourceManager.GetString("SPA21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acerca de....
        '''</summary>
        Public ReadOnly Property SPA22() As String
            Get
                Return ResourceManager.GetString("SPA22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Idioma.
        '''</summary>
        Public ReadOnly Property SPA23() As String
            Get
                Return ResourceManager.GetString("SPA23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inglés.
        '''</summary>
        Public ReadOnly Property SPA24() As String
            Get
                Return ResourceManager.GetString("SPA24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Castellano.
        '''</summary>
        Public ReadOnly Property SPA25() As String
            Get
                Return ResourceManager.GetString("SPA25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  de almacenamiento.
        '''</summary>
        Public ReadOnly Property SPA26() As String
            Get
                Return ResourceManager.GetString("SPA26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Almacenando {0} de {2} volumenes... {1}%.
        '''</summary>
        Public ReadOnly Property SPA27() As String
            Get
                Return ResourceManager.GetString("SPA27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operación cancelada.
        '''</summary>
        Public ReadOnly Property SPA28() As String
            Get
                Return ResourceManager.GetString("SPA28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El tamaño personalizado no puede ser mayor que el tamaño del directorio de entrada..
        '''</summary>
        Public ReadOnly Property SPA29() As String
            Get
                Return ResourceManager.GetString("SPA29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tamaño de directorio: .
        '''</summary>
        Public ReadOnly Property SPA30() As String
            Get
                Return ResourceManager.GetString("SPA30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tamaño personalizado: .
        '''</summary>
        Public ReadOnly Property SPA31() As String
            Get
                Return ResourceManager.GetString("SPA31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se han efectuado cambios en los archivos de la carpeta de origen, ¿Quiere recargar la carpeta ahora?.
        '''</summary>
        Public ReadOnly Property SPA32() As String
            Get
                Return ResourceManager.GetString("SPA32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Spain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property split() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("split", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Splitty_7zip_x64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Splitty_7zip_x64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Splitty_7zip_x86() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Splitty_7zip_x86", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Splitty_PowerISO_x86() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Splitty_PowerISO_x86", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Splitty_WinRAR_x64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Splitty_WinRAR_x64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property Splitty_WinRAR_x86() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Splitty_WinRAR_x86", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property United_States() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("United_States", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
